import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="h-screen flex flex-col justify-center items-center w-full">
          <div className="h-full xl:container flex flex-col justify-center items-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
